export const averias = {
  TIPO: 'averiashfc',
  CODIGO_ZONAL: 'codofcadm',
  CODIGO_REQUERIMIENTO: 'codreq',
  CODIGO_CLIENTE: 'codcli',
  NOMBRE_CLIENTE: 'nomcli',
  CODIGO_CTR: 'codctr',
  DESCRIPCION_CTR: 'desnomctr',
  CODIGO_NODO: 'codnod',
  CODIGO_TROBA: 'nroplano',
  DISTRITO: 'desdtt',
  //direccion -START
  destipvia: 'destipvia',
  desnomvia: 'desnomvia',
  numvia: 'numvia',
  despis: 'despis',
  desint: 'desint',
  desmzn: 'desmzn',
  deslot: 'deslot',
  destipurb: 'destipurb',
  desurb: 'desurb',
  //direccion -END
  FECHA_REGISTRO: 'fec_regist',
  CODIGO_MOTIVO: 'codmotv',
  DETALLE_MOTIVO: 'desmotv',
  TIPO_REQUERIMIENTO: 'tipreqfin',
  DETALLE_TRABAJO: 'desobsordtrab',
  TELEFONO_CONTACTO: 'tel_cont_cc',
  TELEFONO_REFERENCIA: 'tel_cont_ref_cc',
  NUMERO_REITERADA: 'numaverei',
  TIPO_TECNOLOGIA: 'tiptecnologia',
  // CODIGO_SEGMENTO: 'codsegmento',
  // TELEFONO: 'telefono',
  //detalle
  // CODIGO_ORDEN: 'codordtrab',
  // CODIGO_INCIDENCIA: 'codinc',
};