export const gpon = [
  "Reparación GPON",
  "Reparación Gpon Movistar Uno",
  "Reparacion Movistar Total Gpon",
  "Instalación Rutina VA Gpon",
  "Rutina MT GPON MT",
  "Rutina MT GPON MT",
  "Rutina VA GPON MT",
  "Traslado GPON",
  "Instalación rutina MT Gpon",
  "Instalación rutina Bucle Gpon",
  "Traslado GPON Movistar Total",
  "Instalación Movistar uno Gpon",
  "Instalación Gpon Movistar Tot",
  "Instalación Migración Gpon",
  "Instalación Migración Gpon MT",
  "Instalación Migración Gpon MT",
  "Instalación Gpon New",
  "Instalación Movistar uno Gpon",
  "Instalación Gpon Movistar Tot",
  "Instalación Migración HFC a Gpon",
  "Instalación Migración HFC a Gpon CC",
  "Instalación Migración HFC a Gpon CC",
  "Instalación Migración HFC a Gpon",
];